---
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - FILE_MARIADB_ROOT_PASSWORD=/mnt/docker/secrets/mariadb01_root_password_secret.txt
      #- MYSQL_DATABASE=USER_DB_NAME #optional
      #- MYSQL_USER=MYSQL_USER #optional
      #- MYSQL_PASSWORD=DATABASE_PASSWORD #optional
      #- REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /mnt/docker/mariadb01/config:/config
    ports:
      - 3306:3306
    restart: unless-stopped


  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin01
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PMA_ARBITRARY=1 #optional
      #- PMA_ABSOLUTE_URI=https://phpmyadmin.example.com #optional
    volumes:
      - /mnt/docker/phpmyadmin01/config:/config
    ports:
      - 8080:80
    restart: unless-stopped
  

secrets:
  mariadb01_root_password_secret:
    file: /mnt/docker/secrets/mariadb01_root_password_secret.txt


