services:
  esphome:
    container_name: iotutils-esphome
    image: esphome/esphome
    ports:
      - 6052:6052
    environment:
      - TZ=america/los_angeles
      - VIRTUAL_HOST=esphome.crzynet.com
#      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/iotutils/esphome/config:/config:rw
    restart: unless-stopped
    privileged: true
